### ISSUE TITLE
[MPOM-159] Upgrade plexus-component-metadata to 1.7.1 to fix JDK 9 issues

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-parent#403]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** opened **[MPOM-159](https://issues.apache.org/jira/browse/MPOM-159?redirect=false)** and commented

Currently the plexus-component-metadata is on 1.6 which seemed to cause some issues with JDK 9...

---

**Affects:** MAVEN-30

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

MPOM-150

**Comment by bmarwell** [comment]
Duplicate of [MPOM-150](https://issues.apache.org/jira/browse/MPOM-150)
